/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CriteriaRouteImport } from './routes/criteria'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamSlugIndexRouteImport } from './routes/team.$slug.index'
import { Route as TeamSlugCompetitionRouteImport } from './routes/team.$slug.$competition'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CriteriaRoute = CriteriaRouteImport.update({
  id: '/criteria',
  path: '/criteria',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamSlugIndexRoute = TeamSlugIndexRouteImport.update({
  id: '/team/$slug/',
  path: '/team/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamSlugCompetitionRoute = TeamSlugCompetitionRouteImport.update({
  id: '/team/$slug/$competition',
  path: '/team/$slug/$competition',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/criteria': typeof CriteriaRoute
  '/privacy': typeof PrivacyRoute
  '/team/$slug/$competition': typeof TeamSlugCompetitionRoute
  '/team/$slug/': typeof TeamSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/criteria': typeof CriteriaRoute
  '/privacy': typeof PrivacyRoute
  '/team/$slug/$competition': typeof TeamSlugCompetitionRoute
  '/team/$slug': typeof TeamSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/criteria': typeof CriteriaRoute
  '/privacy': typeof PrivacyRoute
  '/team/$slug/$competition': typeof TeamSlugCompetitionRoute
  '/team/$slug/': typeof TeamSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/criteria'
    | '/privacy'
    | '/team/$slug/$competition'
    | '/team/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/criteria'
    | '/privacy'
    | '/team/$slug/$competition'
    | '/team/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/criteria'
    | '/privacy'
    | '/team/$slug/$competition'
    | '/team/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CriteriaRoute: typeof CriteriaRoute
  PrivacyRoute: typeof PrivacyRoute
  TeamSlugCompetitionRoute: typeof TeamSlugCompetitionRoute
  TeamSlugIndexRoute: typeof TeamSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criteria': {
      id: '/criteria'
      path: '/criteria'
      fullPath: '/criteria'
      preLoaderRoute: typeof CriteriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$slug/': {
      id: '/team/$slug/'
      path: '/team/$slug'
      fullPath: '/team/$slug/'
      preLoaderRoute: typeof TeamSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$slug/$competition': {
      id: '/team/$slug/$competition'
      path: '/team/$slug/$competition'
      fullPath: '/team/$slug/$competition'
      preLoaderRoute: typeof TeamSlugCompetitionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CriteriaRoute: CriteriaRoute,
  PrivacyRoute: PrivacyRoute,
  TeamSlugCompetitionRoute: TeamSlugCompetitionRoute,
  TeamSlugIndexRoute: TeamSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
